branches:
  only:
  - master

sudo: required
services:
# - docker
language: node_js
node_js:
- "8"


install:
# - npm install -g mocha babel-cli webpack npm-run-all
- npm install -g mocha babel-cli webpack
- npm install --only=production
- npm install --only=dev
before_script:
# - webpack
script: 
- npm run build
- npm run test-ci
# - docker pull node:8
# - docker build -f ./appprod.Dockerfile -t ass-node:build .
# - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" 
# - docker tag ass-node:build ccnuyan/ass-node:0.0.1
# - travis_wait 30 docker push ccnuyan/ass-node:0.0.1

after_success:
# - docker pull node:8
# - docker build -f ./appprod.Dockerfile -t ass-node:build .
# - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" 
# - docker tag ass-node:build ccnuyan/ass-node:0.0.1
# - travis_wait 30 docker push ccnuyan/ass-node:0.0.1